name: Chat
main: to.joe.j2mc.chat.J2MC_Chat
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Chat formatting module
commands:
  me:
    description: emote your feelings
    usage: /me message
  msg:
    description: private message your friends!
    usage: /msg player message
    aliases: ['tell']
  nsa:
    description: The name's Bond. James Bond.
    usage: /nsa
    permission: j2mc.chat.admin.nsa.toggle
    permission-message: ":frog6:"
  mute:
    description: Mutes another player
    usage: /mute player
    permission: j2mc.chat.admin.mute
    permission-message: "Nope.avi"
  muteall:
    description: Mutes all non admins
    usage: /muteall
    permission: j2mc.chat.admin.muteall
    permission-message: "LOL NO"
  listmute:
    description: Shows muted players
    usage: /listmute
    permission: j2mc.chat.admin.mute
    permission-message: "No"
  reply:
    description: Replies to last message
    usage: /reply message
    aliases: ['rep']
  shush:
    description: Ignore chat
    usage: /shush
    permission: j2mc.chat.admin.shush
    permission-message: "AWOOGA"
  rp:
    description: Send a message to the roleplaying chat
    usage: /rp <message>
  rptoggle:
    description: Toggle viewing the roleplaying chat
    usage: /<command>
permissions:
  j2mc.chat.send:
    default: true
    description: lets user chat
  j2mc.chat.receive:
    default: true
    description: lets user see chat
  j2mc.chat.mute:
    default: false
    description: mutes player
  j2mc.chat.admin.nsa:
    default: false 
    description: NSA
  j2mc.chat.admin.nsa.toggle:
    description: nsa
  j2mc.chat.admin.msg:
    description: lets user see messages sent to admin
  j2mc.chat.admin.mute:
    description: mute
  j2mc.chat.admin.muteall:
    description: muteall
  j2mc.chat.admin.muteall.override:
    description: override muteall
  j2mc.chat.admin.shush:
    description: ignore chat
  j2mc.chat.spectator:
    description: Those without this permission will not receive chat from those with it
  j2mc.chat.capsexempt:
    description: This permission exempts users from caps checking
  j2mc.chat.admin:
    description: access to admin commands
    children:
      j2mc.chat.admin.nsa.toggle: true
      j2mc.chat.admin.msg: true
      j2mc.chat.admin.mute: true
      j2mc.chat.admin.muteall: true
      j2mc.chat.admin.muteall.override: true
      j2mc.chat.admin.shush: true
      j2mc.chat.capsexempt: true
