name: J2MC_Chat
main: to.joe.j2mc.chat.J2MC_Chat
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Chat formatting module
commands:
  me:
    description: emote your feelings
    usage: /me message
  msg:
    description: private message your friends!
    usage: /msg player message
    aliases: ['tell']
  nsa:
    description: The name's Bond. James Bond.
    usage: /nsa
    permission: j2mc.chat.admin.nsa.toggle
    permission-message: ":frog6:"
permissions:
  j2mc.chat.recieve:
    default: true
    description: lets user see chat
  j2mc.chat.mute:
    default: false
    description: mutes player
  j2mc.chat.admin.nsa:
    default: false 
    description: NSA
  j2mc.chat.admin.nsa.toggle:
    description: nsa